# Generated by Django 4.1.1 on 2022-10-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AspectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.TextField(max_length=100)),
                ('icon', models.ImageField(upload_to='web_images')),
                ('field_color', models.IntegerField(verbose_name=1)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='web_images')),
                ('author', models.CharField(max_length=100)),
                ('aspect', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=500)),
                ('course_image', models.ImageField(upload_to='web_images')),
                ('price', models.IntegerField()),
                ('tutor_name', models.CharField(max_length=200)),
                ('tutor_image', models.ImageField(upload_to='web_images')),
                ('reviews', models.CharField(max_length=100)),
                ('likes', models.CharField(max_length=100)),
                ('student_user', models.CharField(max_length=100)),
                ('ratings', models.FloatField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.TextField(max_length=200)),
                ('body', models.TextField(max_length=1569)),
                ('image', models.ImageField(upload_to='web_images')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=500)),
                ('course_image', models.ImageField(upload_to='web_images')),
                ('price', models.IntegerField()),
                ('tutor_name', models.CharField(max_length=200)),
                ('tutor_image', models.ImageField(upload_to='web_images')),
                ('reviews', models.CharField(max_length=100)),
                ('likes', models.CharField(max_length=100)),
                ('student_user', models.CharField(max_length=100)),
                ('ratings', models.FloatField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='web_images')),
                ('portfolio', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='web_images')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='web_images')),
                ('testimony', models.TextField(max_length=500)),
                ('qualifications', models.TextField(max_length=500)),
            ],
        ),
    ]
