# Generated by Django 4.1.1 on 2022-10-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_available_courses', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_instructors', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students_enrolled', models.CharField(max_length=10)),
                ('number_of_uploaded_courses', models.CharField(max_length=10)),
                ('number_of_certified_student', models.CharField(max_length=10)),
                ('number_of_global_instructors', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorldWideStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.CharField(max_length=100)),
            ],
        ),
    ]
