# Generated by Django 4.1.1 on 2022-10-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_number_of_certified_student_webstatistic_number_of_certified_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('course_name',)},
        ),
    ]
