# Generated by Django 4.1.1 on 2022-10-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_course_about_tutor_remove_course_tutor_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_name', models.CharField(max_length=200)),
                ('tutor_image', models.ImageField(upload_to='web_images')),
                ('tutor_portfoilo', models.TextField(max_length=35)),
                ('about_tutor', models.TextField(max_length=350)),
            ],
        ),
    ]
