# Generated by Django 4.1.1 on 2022-10-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_instructor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='about_tutor',
            field=models.TextField(default=0, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='tutor_image',
            field=models.ImageField(default=0, upload_to='web_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='tutor_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='tutor_portfoilo',
            field=models.TextField(default=0, max_length=35),
            preserve_default=False,
        ),
    ]
